services:
  - type: web
    name: bg-removal-app
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: CLIPDROP_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
